ktor {
    deployment {
        port = 8080
        port = ${?WANTLY_PORT}
        shutdownGracePeriod = 2000
        shutdownTimeout = 5000
    }
    application {
        modules = [com.nervs.wantly.backend.ApplicationKt.module]
    }
}
db {
    url = "jdbc:postgresql://localhost:5432/wantly"
    url = ${?WANTLY_DB_URL}
    user = "wantly"
    user = ${?WANTLY_DB_USER}
    password = "wantly_dev_2026"
    password = ${?WANTLY_DB_PASSWORD}
}
